title: 인하대학교 인트아이
description: 인하대학교 정보통신공학과 프로그래밍 소모임 인트아이 스터디 블로그
url: https://int-i.github.io
baseurl: ""
timezone: Asia/Seoul
permalink: /:categories/:year-:month-:day/:title/

email: iceinti16@gmail.com
manager: yt4307

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

feed:
  path: atom.xml

kramdown:
  input: GFM

excerpt_separator: "##"

paginate: 5
paginate_path: /page/:num/

sass:
  style: compressed
