title: "인하대학교 인트아이"
description: "인하대학교 정보통신공학과 프로그래밍 소모임 인트아이 기술 블로그"
url: "https://int-i.github.io/"
timezone: Asia/Seoul
permalink: /:categories/:year-:month-:day/:title/

author:
  name: 인하대학교 인트아이
  email: int-i@example.com
  tel: 010-1234-5678

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

plugins:
  - jekyll-feed
  - jekyll-paginate

feed:
  path: atom.xml

kramdown:
  input: GFM

paginate: 5
paginate_path: "/page/:num/"

sass:
  style: compressed
